### ISSUE TITLE
Error: No such session: default

### ISSUE THREAD

**Issue by VectorWorkshop** [zhaytee/matrix-rpc-bot#13]
I've been trying to write bot in python and run into issue.

```
startSessionRequest = matrix_bot_pb2.StartSessionRequest(
    session_id = "default",               # created session with sessin_id - "default"
    homeserver = home_server,
    user_id = user_id,
    display_name = "bot",
    device_id = device_id,
    access_token = access_token)
responce = stub.StartSession(startSessionRequest)

sendMessageRequest = matrix_bot_pb2.SendTextMessageRequest(
    session_id = "default",               # tried to send message with that session id 
    room_id="",
    body="I'm bot")
responce = stub.SendTextMessage(sendMessageRequest)
```

Server got 

```
Error: No such session: default
    at Object.sendTextMessage (/home/user/matrix-rpc-bot/src/grpc_server.ts:184:19)
    at handleUnary (/home/user/matrix-rpc-bot/node_modules/@grpc/grpc-js/src/server.ts:896:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
...
```

I tried changing session id but no difference

Thank you for your work to make Matrix bots finally End to End Encrypted! 😀

**Comment by zhaytee** [comment]
Hi @VectorWorkshop. The issue here is that the Matrix client needs some time to start up before you can call SendTextMessage and other functions.

To make this easier, matrix-rpc-bot will send an event called "XReady". Once your code has received that event, it should be safe to use all other calls.

In Python, to iterate over the event stream, you can use a construct like this: `for session_event in stub.StartSession(...):`; see https://grpc.io/docs/languages/python/basics/#response-streaming-rpc-1

Then you can handle each event by inspecting the "content" field: https://github.com/zhaytee/matrix-rpc-bot/blob/master/proto/matrix.proto#L128

The "content" field is a special "oneof" field, which can be handled in Python as described here: https://developers.google.com/protocol-buffers/docs/reference/python-generated#oneof

**Comment by VectorWorkshop** [comment]
Hi @zhaytee, thanks for the answer and links to the documentation
Now I got
```RuntimeError: abort(TypeError: this.baseApis.crypto.sessionStore.getLocalTrustedBackupPubKey is not a function).```

With this code in python client.
```
startSessionRequest = matrix_bot_pb2.StartSessionRequest(
    session_id = "default",
    homeserver = home_server,                          # figured out it has to start with https:\\
    user_id = user_id,                                 # @nobody:matrix.org
    display_name = "Bot",
    device_id = device_id,                             # 10 symbols
    access_token = access_token,                       # long string
    initial_presence = matrix_bot_pb2.PRESENCE_ONLINE) # or just 1
    # state_root_path, avatar_url - are optional?

for session_event in stub.StartSession(startSessionRequest):
    assert session_event.WhichOneof("test_oneof")
```

Is my request is correct? What's wrong?

**Comment by zhaytee** [comment]
Hi @VectorWorkshop , I'm not actually sure about this. Something is going wrong with the Matrix Javascript SDK. Sometimes this can happen if data isn't being persisted correctly to disk, or gets corrupted. By default, that data is written to `~/.local/matrix-rpc-bot-{sessionid}-{deviceid}`, so you might want to try deleting that dir and then restarting matrix-rpc-bot.
